$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_timeseries_forecaster
display_name: Train XGBoost Forecaster
description: Treina um modelo XGBoost para previsão de séries temporais.
version: 4

inputs:
  processed_data:
    type: uri_folder

code: ../src/

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  conda_file: ./environment.yml

command: >-
  python train_forecast_model.py
  --processed_data ${{inputs.processed_data}}