$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_timeseries_forecaster
display_name: Train Time Series Forecaster
description: Treina um modelo XGBoost para previsão de séries temporais.
version: 1

inputs:
  processed_data:
    type: uri_folder

outputs:
  trained_model:
    type: mlflow_model

code: ../src/

environment:
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  conda_file: ./get_data_env.yml

command: >-
  python train_forecast_model.py
  --processed_data ${{inputs.processed_data}}
  --trained_model ${{outputs.trained_model}}